my_file = open('1001.txt',"r")
rd1 = int(my_file.readline())
rd2 = int(my_file.readline())
rd3 = int(my_file.readline())
my_file.close()
rplus = str(rd1 + rd2 + rd3)
my_file1 = open('1003.txt', 'w')
my_file1.write(rplus)
my_file1.close()
print('Succes')
input()
