my_file = open("meed.txt","r")
my_file1 = open('meed1.txt','r')
my_string = int(my_file.read())
my_string1 = int(my_file1.read())
print("Counting:")
print(str(my_string + my_string1))
my_file2 = open('Count.txt', 'w')
my_file2.write(str(my_string + my_string1))
print('Recorded')
my_file.close()
my_file1.close()
my_file2.close()
input()
